framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        # The Tailwind source is compiled to assets/build/app.css by pnpm.
        excluded_patterns:
            - '*/assets/styles/app.css'
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
